# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: sarajanedeveloper@gmail.com
author_name: SaraJane
cloud_provider: vercel
contract_name: hello_world
preset_name: production
project_name: TokenizeRWATemplate

